[general]
live_config_reload = true

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
# WINIT_HIDPI_FACTOR = "1.0"

[selection]
save_to_clipboard = true

[font]
size = 11.5

[font.normal]
# family = 'FiraCode Nerd Font'
# family = 'IosevkaTerm Nerd Font Mono'
family = 'JetBrainsMono Nerd Font'

# Colors (Gruvbox Material Hard Dark) ============

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# ================================================
